# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Entry_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from main import MainWindow  # Import the MainWindow class from main.py


def resource_path(relative_path: str) -> str:
    """Return absolute path to resource, works for dev and for PyInstaller --onefile."""
    base_path = getattr(sys, '_MEIPASS', os.path.abspath('.'))
    return os.path.join(base_path, relative_path)

class Ui_Dialog(object):
    def openMainWindow(self):
        # Instantiate and show the MainWindow subclass directly so
        # its constructor (__init__) runs and timers/plots/serial are active.
        # pass entered port/baud to MainWindow (fall back to defaults if not provided)
        port = getattr(self, 'port', None)
        baud = getattr(self, 'baud', None)
        self.window = MainWindow(port, baud)
        self.window.show()

    def changePORTBAUD(self):
        # Get the text from the text edits and store them in variables
        # store values on the dialog instance for later use
        self.port = self.textEdit.toPlainText().strip()
        self.baud = self.textEdit_2.toPlainText().strip()

    def handleButtonClick(self):
        self.changePORTBAUD()  # Update PORT and BAUD values
        # Open the main window
        self.openMainWindow()

    def setupUi(self, Dialog):
        Dialog.setObjectName("First Dialog")
        Dialog.setFixedSize(689, 591)
        Dialog.setWindowIcon(QIcon(resource_path('cropped-aiaaweblogo.png')))  # Set the window icon to the AIAA logo
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 651, 551))
        self.groupBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
                                        "font: 75 11pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 270, 241, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 270, 111, 71))
        self.label_2.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(210, 190, 241, 71))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 190, 111, 71))
        self.label.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox, clicked = self.handleButtonClick)
        self.pushButton.setGeometry(QtCore.QRect(200, 410, 251, 81))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(470, 0, 161, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(resource_path('cropped-aiaaweblogo.png')))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Ground Station App 2025-2026", "Ground Station App 2025-2026"))
        self.groupBox.setTitle(_translate("Dialog", "AIAA Ground Station App"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Ex: 9600</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "BAUD"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Ex: COM3</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "Port"))
        self.pushButton.setText(_translate("Dialog", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
